smsproj/urls.py
from django.contrib import admin
from django.urls import path
from smsapp import views
from users import views as user_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/', views.home, name="home"),
    path('', views.home, name="home"),
    path('newvoicetemplate/', views.upload_audio, name="createvoicetemplate"),
    path('audiolist/', views.audiolist, name="recordlist"),
    path('grouplist/', views.grouplist, name="grouplist"),
    path('newbmessagecat/', views.createbmessagecat, name="createbmessagecat"),
    path('newvoicebroadcast/', views.createvoicebroad, name="newvoicebroadcast"),

    #path('newbmessagedis/', views.createbmessagedis, name="createbmessagedis"),
    path('newbmessageall/', views.createbmessageall, name="createbmessageall"),
    path('newgroup/', views.creategroup, name="creategroup"),
    path('newmesstemp/', views.messtemp, name="messtemp"),
    path('templatelist/', views.templatelist, name="templatelist"),
    path('deliverylist/', views.deliverylist, name="deliverylist"),
    path('responselog/', views.responselog, name="responselog"),
	path('sync/', views.update_delivery_records, name="sync"),

    	
    path('download/', views.deliverylist, name="download"),
    path('bcriteria/', views.bcriteria, name="bcriteria"),
    path('vcriteria/', views.vcriteria, name="vcriteria"),

    path('ajax/load-grades/', views.load_grades, name='ajax_load_grades'),
    path('ajax/validate_empnumber/', views.validate_empnumber, name='validate_empnumber'),
    
    path('updaterecord/<str:pk>/', views.updaterecord, name="updaterecord"),
    path('recordsupdate/<str:pk>/', views.records_update, name="recordsupdate"),
    path('record_create/', views.upload_audio, name="record_create"),
    path('trying/', views.trying, name='trying'),
    
    
    
    
    #paths for the users app
    path('register/', user_views.register, name="register"),
    path('login/', user_views.loginpage, name="login"),
    path('logout/', user_views.logoutuser, name="logoutuser"),
]

admin.site.site_header = "Welcome to ACHF SMS Portal"
admin.site.site_title = "AHCF Admin Portal"
admin.site.index_title = "AHCF SMSApp Admin"

smsapp/models.py
from django.db import models

from datetime import datetime    


# Create your models here.
class region(models.Model):
	regionName = models.CharField(max_length = 100)
	
	def __str__(self):
		return self.regionName
	
class district(models.Model):
	districtName = models.CharField(max_length= 100)
	region = models.ForeignKey(region, null=True, on_delete=models.SET_NULL)
	
	def __str__(self):
		return self.districtName
	
class subdistrict(models.Model):
	subdistrictName = models.CharField(max_length=100)
	district = models.ForeignKey(district, null=True, on_delete=models.SET_NULL)
	
	def __str__(self):
		return self.subdistrictName
	
class bmc(models.Model):
	bmcName = models.CharField(max_length=100)
	subdistrict = models.ForeignKey(subdistrict, null=True, on_delete=models.SET_NULL)
	
	class Meta:
		ordering = ('bmcName',)
	
	def __str__(self):
		return self.bmcName
		

	
class group(models.Model):
	
	groupName = models.CharField(max_length=100)
	
	def __str__(self):
		return self.groupName


	
class unit(models.Model):
	unit = models.CharField(max_length=100)
	
	def __str__(self):
		return self.unit


class category(models.Model):
	catName = models.CharField(max_length=100)
	
	class Meta:
		verbose_name_plural='Categories'
		
	def __str__(self):
		return self.catName
		
class grade(models.Model):
	grade = models.CharField(max_length=100)
	category = models.ForeignKey(category, null=True, on_delete=models.SET_NULL)
	
	class Meta:
		ordering = ('grade',)
	
	def __str__(self):
		return self.grade 

class records(models.Model):
	GENDER = (
			 ('Male', 'Male'),
			 ('Female', 'Female'),
			
			 )
	TITLE = (
			 ('Mr.', 'Mr.'),
			 ('Mrs.', 'Mrs.'),
			 ('Miss.', 'Miss'),
			 ('Dr.', 'Dr.'),
			
			 )
			 		 
	MARITAL_STATUS = (
			 ('Single', 'Single'),
			 ('Married', 'Married'),
			 ('Divorced', 'Divorced'),
			 ('Widowed', 'Widowed'),
			
			 )
			 
	RELIGION = (
			 ('Christian', 'Christian'),
			 ('Muslim', 'Muslim'),
			 ('Other', 'Other'),
			
			 )
			 
	STATUS = (
			 ('Active', 'Active'),
			 ('Inactive', 'Inactive'),
			
			 )
	
	EmpNumber = models.CharField(max_length=15,primary_key=True, verbose_name='Employment Number')
	Title = models.CharField(max_length=11, choices=TITLE, default=TITLE[0][0],null=True, blank=True)
	FirstName = models.CharField(max_length=50, verbose_name='First Name')
	LastName = models.CharField(max_length=50, verbose_name='Last Name')
	OtherName = models.CharField(max_length=50, verbose_name='Other Name', null=True, blank=True)
	Gender = models.CharField(max_length=10, choices=GENDER)
	DOB = models.DateField(verbose_name='Date of Birth')
	MaritalStatus = models.CharField(max_length=10, choices=MARITAL_STATUS, verbose_name='Marital Status', null=True, blank=True)
	Religion = models.CharField(max_length=10, choices=RELIGION, blank=True)
	OfficialEmail= models.CharField(max_length=50,verbose_name='Official Email', unique=True, null=True, blank=True)
	PersonalEmail= models.CharField(max_length=50, verbose_name='Personal Email',null=True, blank=True)
	Mobile = models.CharField(max_length=10, verbose_name='1st Mobile', unique=True)
	Mobile1 = models.CharField(max_length=10,verbose_name='2nd Mobile', null=True, blank=True)
	FirstAppDate = models.DateField(verbose_name='First Appointment Date')
	AssumptionDutyDate= models.DateField(verbose_name='Date of Assumption of Duty')
	category = models.ForeignKey(category, null=True, verbose_name='Category', on_delete=models.SET_NULL)
	grade = models.ForeignKey(grade, null=True, on_delete=models.SET_NULL)
	bmc = models.ForeignKey(bmc, null=True, verbose_name='BMC', on_delete=models.SET_NULL)
	unit = models.ForeignKey(unit, null=True, on_delete=models.SET_NULL, blank=True)
	status = models.CharField(max_length=10, choices=STATUS, default=STATUS[0][0], null=True)
	date_created = models.DateTimeField(default=datetime.now, null=True)
	date_updated = models.DateTimeField(auto_now=True, null=True)
	
	class Meta:
		verbose_name_plural = 'records'
	
	def __str__(self):
		return self.FirstName

class theme(models.Model):
	theme = models.CharField(max_length= 100)
	description = models.CharField(max_length= 100, null=True)
	
	def __str__(self):
		return self.theme


class broadcastmessagedis(models.Model):
	
	
	Subject=models.CharField(max_length=50)
	Content=models.CharField(max_length=400)
	district=models.ForeignKey(district, null=True, on_delete=models.SET_NULL)
	
	
	class Meta:
		verbose_name_plural='District-based Broadcast Messages'
	
	def __str__(self):
		return self.Subject


class broadcastmessagecat(models.Model):
	
	theme=models.ForeignKey(theme, null=True, on_delete=models.SET_NULL)
	Content=models.CharField(max_length=400)
	category=models.ForeignKey(category, null=True, on_delete=models.SET_NULL)
	
	
	
	class Meta:
		verbose_name_plural='Category-based Broadcast Messages'
	
	def __str__(self):
		return self.Subject

class broadcastmessageall(models.Model):
	Subject=models.CharField(max_length=50)
	Content=models.CharField(max_length=400)
	
	class Meta:
		verbose_name_plural='Broadcast Messages to all'
	
	def __str__(self):
		return self.Subject

class delivery(models.Model):
	sms_status = models.CharField(max_length=50, null=True, blank=True)
	smstype = models.CharField(max_length=50, null=True, blank=True)
	total_sent = models.CharField(max_length=50, null=True, blank=True)
	total_rejected = models.CharField(max_length=50, null=True, blank=True)
	recipient=models.CharField(max_length=50, null=True, blank=True)
	catname=models.CharField(max_length=50,null=True, blank=True)
	name=models.CharField(max_length=50, null=True, blank=True)
	age=models.IntegerField(null=True, blank=True)
	gender=models.CharField(max_length=50, null=True, blank=True)
	project=models.CharField(max_length=50, null=True, blank=True)
	region=models.CharField(max_length=50, null=True, blank=True)
	district=models.CharField(max_length=50, null=True, blank=True)
	pregnancy_status=models.CharField(max_length=50,null=True, blank=True)
	caregiver=models.CharField(max_length=50, null=True, blank=True)
	lactating=models.CharField(max_length=50, null=True, blank=True)
	credit_used = models.CharField(max_length=50, null=True, blank=True)
	credit_left = models.CharField(max_length=50, null=True, blank=True)
	call_id=models.CharField(max_length=50, null=True, blank=True)
	answer_time=models.CharField(max_length=50, null=True, blank=True)
	hang_up_time=models.CharField(max_length=50, null=True, blank=True)
	answer_period=models.CharField(max_length=50, null=True, blank=True)
	date_created = models.DateTimeField(auto_now_add=True)
	
	class Meta:
		verbose_name_plural = 'Deliveries'
	
	def __str__(self):
		return self.sms_status


class AudioFile(models.Model):
	name = models.CharField(max_length=50, null=True)
	description = models.TextField(max_length=200,blank=True)
	file = models.FileField(upload_to='audio/')
	uploaded_at = models.DateTimeField(auto_now_add=True)
	
	def __str__(self):
		return self.name or ''

class project(models.Model):
	projectName = models.CharField(max_length= 100)
	region = models.ForeignKey(region, null=True, on_delete=models.SET_NULL)
	
	def __str__(self):
		return self.projectName

class ResponseLog(models.Model):
    status = models.CharField(max_length=255)
    code = models.CharField(max_length=255)
    message = models.TextField()
    smstype=models.CharField(max_length=50, null=True, blank=True)
    recipient=models.CharField(max_length=50, null=True, blank=True)
    name=models.CharField(max_length=50, null=True, blank=True)
    timestamp = models.DateTimeField(auto_now_add=True)

	
    def __str__(self):
        return f"{self.timestamp} - {self.status}: {self.message}"

smsapp/forms.py
from django import forms  
from smsapp.models import AudioFile, records, group, broadcastmessagecat, broadcastmessagedis,broadcastmessageall, grade


class RecordsForm(forms.ModelForm):
	class Meta:
		model = records
		exclude = ['status','group']
		
		widgets = {
            'EmpNumber': forms.TextInput (attrs={'class': 'form-control', 'placeholder':'Enter employment number'}),
            'Title': forms.Select (attrs={'class': 'form-control'}),
            'FirstName': forms.TextInput (attrs={'class': 'form-control', 'placeholder':'First Name'}),
            'LastName': forms.TextInput (attrs={'class': 'form-control', 'placeholder':'Last Name'}),
            'OtherName': forms.TextInput (attrs={'class': 'form-control', 'placeholder':'Other Name'}),
            'Gender': forms.Select (attrs={'class': 'form-control'}),
            'DOB': forms.TextInput (attrs={'type':'date', 'class': 'form-control'}),
            'MaritalStatus': forms.Select (attrs={'class': 'form-control'}),
            'Religion': forms.Select (attrs={'class': 'form-control'}),
            'OfficialEmail': forms.EmailInput (attrs={'type':'email', 'class': 'form-control', 'placeholder':'Eg: joe@email.com'}),
            'PersonalEmail': forms.EmailInput (attrs={'class': 'form-control', 'placeholder':'Eg: joe@email.com'}),
            'Mobile': forms.TextInput (attrs={'class': 'form-control', 'placeholder':'10 digits number', 'title':'Must be 10 digits only', 'pattern':'\d{10}'}),
            'Mobile1': forms.TextInput (attrs={'class': 'form-control', 'placeholder':'10 digits number'}),
            'FirstAppDate': forms.TextInput (attrs={'type':'date', 'class': 'form-control'}),
            'AssumptionDutyDate': forms.TextInput (attrs={'type':'date', 'class': 'form-control'}),
            'category': forms.Select (attrs={'class': 'form-control'}),
            'grade': forms.Select (attrs={'class': 'form-control'}),
            'bmc': forms.Select (attrs={'class': 'form-control'}),
            'unit': forms.Select (attrs={'class': 'form-control'}),
            
           # 'group': forms.Select (attrs={'class': 'form-control'}),
            
        }
        
	def __init__(self, *args, **kwargs):
		super().__init__(*args, **kwargs)
		self.fields['grade'].queryset = grade.objects.none()
        
		if 'category' in self.data:
			try:
				category_id = int(self.data.get('category'))
				self.fields['grade'].queryset = grade.objects.filter(category_id=category_id).order_by('grade')
			except (ValueError, TypeError):
				pass  # invalid input from the client; ignore and fallback to empty City queryset
		elif self.instance.pk:
			self.fields['grade'].queryset = self.instance.category.grade_set.order_by('grade')

        
        
class BroadcastmessagecatForm(forms.ModelForm):
	class Meta:
		model = broadcastmessagecat
		fields = '__all__'
		
		widgets = {
			'theme': forms.Select (attrs={'class': 'form-control'}),
			'Content': forms.Textarea (attrs={'class': 'form-control', "rows":5, 'placeholder':'Enter the content of your message here'}),
			'category':forms.Select (attrs={'class': 'form-control'}),
            #'Group': forms.Select (attrs={'class': 'form-control'}),
        
            
        }

class BroadcastmessageallForm(forms.ModelForm):
	class Meta:
		model = broadcastmessageall
		fields = '__all__'
		
		widgets = {
			'Subject': forms.TextInput (attrs={'class': 'form-control', 'placeholder':'Eg: Pin Renewal'}),
			'Content': forms.Textarea (attrs={'class': 'form-control', "rows":5, 'placeholder':'Enter the content of your message here'}),
			#'category':forms.SelectMultiple (attrs={'class': 'form-control'}),
            #'Group': forms.Select (attrs={'class': 'form-control'}),
        
            
        }
        
class BroadcastmessagedisForm(forms.ModelForm):
	class Meta:
		model = broadcastmessagedis
		fields = '__all__'
		
		widgets = {
			'Subject': forms.TextInput (attrs={'class': 'form-control', 'placeholder':'Eg: Pin Renewal'}),
			'Content': forms.Textarea (attrs={'class': 'form-control', "rows":5, 'placeholder':'Enter the content of your message here'}),
			'district':forms.Select (attrs={'class': 'form-control'}),
            #'Group': forms.Select (attrs={'class': 'form-control'}),
        
            
        }

class GroupForm(forms.ModelForm):
	class Meta:
		model = group
		fields = '__all__'
		
		widgets = {
            'groupName': forms.TextInput (attrs={'class': 'form-control'}),
        
        }

class AudioFileForm(forms.ModelForm):
    class Meta:
        model = AudioFile
        #fields = ('file',)
        fields = '__all__'
        

smsapp/templates/smsapp/audiolist.html
{% extends 'smsapp/base.html' %}

{% load static %}

{% block title %} <title>Records</title> {% endblock %}





{% block content %}


<div class="row">
	<div class="col-md-12">
		<div class="col-md">
			<a class="btn btn-md btn-primary" href="{% url 'createvoicetemplate' %}">Create Voice Template</a>
		</div>
		<hr>
		<div class="card card-body">
			
			<table class="table table-sm table-striped">
				<thead class="thead-dark">
				<tr>
					<th>Name</th>
					<th>Description</th>
					<th>File</th>
					<th>Delete</th>
				</tr>
				</thead>
				{% for audio in audios %}
				<tr>
					<td>{{ audio.name }}</td>
					<td>{{ audio.description }}</td>
					<td>{{ audio.file }}</a></td>
					<td><a class="btn btn-sm btn-danger" disabled>Delete</a></td>
				</tr>
				{% empty %}
				<tr>
				  <td colspan="10" class="text-center bg-warning">No Records</td>
				</tr>
				{% endfor %}
			</table>
		</div>
	</div>
	
{% endblock %}

smsapp/templates/smsapp/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  {% block title %} <title>Base Template</title> {% endblock %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  
<!-- CDN links -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" 
  integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  
  
<!--links to static files-->
  <link rel="stylesheet" type="text/css" href="{% static 'css/sticky-footer-navbar.css' %}">
  
  

</head>

<body id="index" class="home">

	<details>
  <summary>Notification Desk</summary>
  <p><h2>Wear a mask, Clean your hands, Keep a safe distance</h2></p>
	</details>


<header>
      <!-- Fixed navbar -->
      <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
        <a class="navbar-brand" href="{% url 'home' %}">
			<!--<img src="{% static 'images/xxx.jpeg' %}" alt="Logo" style="width:40px;">-->
			<b>ACHF</b>
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item">
				<a class="nav-link" href="{% url 'recordlist' %}">Voice Templates</a>
			</li>
			<li class="nav-item">
				<a class="nav-link" href="{% url 'deliverylist' %}">Sent Notifications</a>
			</li>
			<li class="nav-item">
				<a class="nav-link" href="{% url 'responselog' %}">Response Logs</a>
			</li>
          </ul>
          
          {% if user.is_authenticated %}
		  <span>
			  <li class="nav-item">
				<a class="nav-link" href=""><b>Hello, {{request.user}}</b></a>
			  </li>
		  </span>
		  <span>
			   <li class="nav-item">
				<a class="nav-link" href="{% url 'logoutuser' %}"><b>Logout</b></a>
			  </li>
		  </span>
		  {% else %}
		   <span>
			   <li class="nav-item">
				<a class="nav-link" href="{% url 'login' %}"><b>Login</b></a>
			  </li>
		  </span>
		  {%  endif %}
        </div>
        
        
      </nav>
</header>
<main role="main" class="container">
	<div class="row">
		<div class="col-md-12">
			{% if messages %}
			{% for message in messages.get_messages %}
				{% if 'saving' in message.tags %}
					<div class="alert alert-{{message.tags}}">
						{{ message }}
					</div>
				{% elif 'saved' in message.tags %}
					<div class="alert alert-{{message.tags}}">
						{{ message }}
					</div>
				{% elif 'authenticating' in message.tags %}
					<div class="alert alert-{{message.tags}}">
						{{ message }}
					</div>
				{% elif 'authenticated' in message.tags %}
					<div class="alert alert-{{message.tags}}">
						{{ message }}
					</div>
				{% elif 'retrieving' in message.tags %}
					<div class="alert alert-{{message.tags}}">
						{{ message }}
					</div>
				{% elif 'sending' in message.tags %}
					<div class="alert alert-{{message.tags}}">
						{{ message }}
					</div>
			{% endif %}
			{% endfor %}
			{% endif %}
			

		</div>
	</div>
</main>
{% block content %}
<br><br>


{% endblock %}






</body>



<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

 <script>
    $("#id_category").change(function () {
      const url = $("#recordForm").attr("data-grades-url");  // get the url of the `load_cities` view
      const categoryId = $(this).val();  // get the selected country ID from the HTML input
      
      
      $.ajax({                       // initialize an AJAX request
        url: url,                    // set the url of the request (= localhost:8000/hr/ajax/load_grades/)
        data: {
          'category_id': categoryId       // add the country id to the GET parameters
        },
        success: function (data) {   // `data` is the return of the `load_cities` view function
          console.log(data);
          $("#id_grade").html(data);  // replace the contents of the city input with the data that came from the server
        }
      });

    });
 </script>
 
<script>
	$("#id_EmpNumber").change(function () {
		const empnumber = $(this).val();
		const url = $("#recordForm").attr("empnumbvalidate-url");
		console.log( $(this).val() );

		$.ajax({
           url: url,
           data: {
			'EmpNumber': empnumber       // add the country id to the GET parameters
		   },
		   
		   success: function (data) {
			   if (data.is_taken){
				   alert("A record with this Employment Number already exists.")
			   }
			}
        });
    });
</script>
 
<script>
    $(".js-create-record").click(function () {
      $.ajax({                       // initialize an AJAX request
        url: "{% url 'record_create' %}",                    // set the url of the request (= localhost:8000/hr/ajax/load_grades/)
		type: 'get',
		dataType: 'json',
		beforeSend: function(){
			$("#modal-records").modal("show");
		},
        success: function (data) {
        $("#modal-records .modal-content").html(data.html_form);
      	}
      });

    });
 </script>
 
 
<script type="text/javascript">
window.onload = function(){
document.getElementById('criteria').onchange = function() {
    var i = 1;
    var myDiv = document.getElementById(i);
    while(myDiv) {
        myDiv.style.display = 'none';
        myDiv = document.getElementById(++i);
    }
    document.getElementById(this.value).style.display = 'block';
}};
</script> 

 <noscript>
         Sorry...JavaScript is needed to go ahead.
 </noscript>

</html>

smsapp/templates/smsapp/bcmessagecatfrm.html
{% extends 'smsapp/base.html' %}

{% load static %}

{% block title %} <title>Broadcast Message Form</title> {% endblock %}





{% block content %}

<style>
.myform {
  margin: 70px 450px;
}
</style>


<div class="myform">
<div class="jumbotron">
	<h3>Create a Broadcast Message</h3>
	<br>
<form action="" method="POST">
  {% csrf_token %}
	
  {{fm.as_p}}
  <br>
  <button type="submit" class="btn btn-primary">Send Broadcast</button>
  <a class="btn btn-primary" href="{% url 'home' %}">Cancel</a>
</form>
</div>
</div>

{% endblock %}

smsapp/templates/smsapp/dashboard.html
{% extends 'smsapp/base.html' %}

{% load static %}

{% block title %} <title>Dashboard</title> {% endblock %}

{% block content %}

<br>
<div class="row">
	
	<div class="col">
		<div class="col-md">
			<div class="card text-center text-dark mb-3" id="total orders">
				<div class="card-header">
					<h5 class="card-title">Voice Call Balance:</h5>
				</div>
				<div class="card-body">
					<table class="table table-sm">
				<tr>
					<th>Message Cat 1</th>
					<th>Message Cat 2</th>
					<th>Message Cat 3</th>
				</tr>
				<tr>
					<td>{{ recodsnum }}</td>
					<td>{{ activenum }}</td>
					<td>{{ inactivenum }}</td>
				</tr>
				<a class="btn btn-primary  btn-sm btn-block" href="{% url 'vcriteria' %}">Create Voice Broadcast</a>
					</table>
				</div>
			</div>
		</div>
	</div>



	<div class="col">
		<div class="col-md">
			<div class="card text-center text-dark mb-3" id="orders delivered">
				<div class="card-header">
					<h5 class="card-title">SMS Balance:</h5>
				</div>
				<div class="card-body">
					<table class="table table-sm">
				<tr>
					
					<th>Message Cat 1</th>
					
					<th>Message Cat 2</th>
					<th>Message Cat 3</th>
					
					<th>Message Cat 4</th>
				</tr>
				
				<tr>
					
					<td>{{ bdaysms }}</td>
					
					<td>{{ annisms }}</td>
					<td>{{ welsms }}</td>					
					<td>{{ bsms }}</td>
				</tr>
				<a class="btn btn-primary btn-sm btn-block" href="{% url 'bcriteria' %}">Create SMS Broadcast</a>
						 
					</table>
				</div>
			</div>
		</div>
	</div>

</div>

<!-- <div class="row">
	<div class="col-md-7">
		<div class="col-md-7">
		<h5>New Registrations (Last 5):</h5>
		</div>
		<hr>
		<div class="card card-body">
			
			<table class="table table-sm table-striped table-responsive">
				<thead class="thead-dark">
				<tr>
					<th>First Name</th>
					<th>Last Name</th>
					<th>District</th>
					<th>Bmc</th>
					<th>Grade</th>
					<th>Timestamp</th>
					
					
				</tr>
				</thead>
				{% for record in recods %}
				<tr>
					<td>{{ record.FirstName }}</a></td>
					<td>{{ record.LastName }}</td>
					<td>{{ record.bmc.subdistrict.district }}</td>
					<td>{{ record.bmc }}</td>
					<td>{{ record.grade }}</td>
					<td>{{ record.date_created }}</td>
					
					
				</tr>
				{% endfor %}
			</table>
		</div>
	</div> -->

	<div class="col-md-12">
		<h5>Sent Notifications (Last 5):</h5>
		<hr>
		<div class="card card-body">
			<table class="table table-sm table-striped table-responsive">
				<thead class="thead-dark">
				<tr>
					<th>Delivery Status</th>
					<th>Recipient</th>
					<th>Total Sent</th>
					<th>Total Rejected</th>
					<th>Credit Used</th>
					<th>Credit Left</th>
					<th>Timestamp</th>
				</tr>
				</thead>
				
				{% for delivery in deliveries %}
				<tr>	
					<td>{{ delivery.sms_status}}</td>
					<td>{{ delivery.recipient }}</td>
					<td>{{ delivery.total_sent }}</td>
					<td>{{ delivery.total_rejected }}</td>
					<td>{{ delivery.credit_used }}</td>
					<td>{{ delivery.credit_left }}</td>
					<td>{{  delivery.date_created }}</td>
					
				</tr>
				{% endfor %}
			</table>
		</div>
	</div>
</div>
</div

{% endblock %}

smsapp/templates/smsapp/districts_dropdown_list_options.html
<option value=""></option>
{% for district in districts %}
<option value="{{ district.pk }}">{{ district.districts }}</option>
{% endfor %}

smsapp/templates/smsapp/grades_dropdown_list_options.html
<option value=""></option>
{% for gr in grades %}
<option value="{{ gr.pk }}">{{ gr.grade }}</option>
{% endfor %}

smsapp/templates/smsapp/groups.html
{% extends 'smsapp/base.html' %}

{% load static %}

{% block title %} <title>Groups</title> {% endblock %}





{% block content %}


<div class="row">
	<div class="col-md-12">
		<h5>Group List</h5>
		<hr>
		<div class="card card-body">
			
			<table class="table">
				<tr>
					<th>Group Name</th>
					<th>Update</th>
					<th>Delete</th>

				</tr>
				{% for group in grps %}
				<tr>
					<td>{{ group.groupName }}</td>
					<td><a class="btn btn-sm btn-info" href="">Update</a></td>
					<td><a class="btn btn-sm btn-info" href="">Delete</a></td>
					
				</tr>
				{% endfor %}
				<a class="btn btn-primary btn-sm btn-block"  href="{% url 'creategroup' %}">Create New Group</a>
			</table>
		</div>
	</div>

{% endblock %}